
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "683d5ad91eeb41aee3d784237cd3a5cce4ecfda0",
 "version": "0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
